/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PublicTaskImport } from './routes/_public/task'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as PrivateResourcesImport } from './routes/_private/resources'
import { Route as PrivateProjectsImport } from './routes/_private/projects'
import { Route as PrivateLogoutImport } from './routes/_private/logout'
import { Route as PrivateCodesImport } from './routes/_private/codes'
import { Route as PrivateClientsImport } from './routes/_private/clients'
import { Route as PrivateAsociatesImport } from './routes/_private/asociates'
import { Route as PrivateUserIdImport } from './routes/_private/user_.$id'
import { Route as PrivateTasksTaskIdImport } from './routes/_private/tasks.$taskId'
import { Route as PrivateProjectsProjectIdImport } from './routes/_private/projects_.$projectId'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicTaskRoute = PublicTaskImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const PrivateResourcesRoute = PrivateResourcesImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProjectsRoute = PrivateProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateLogoutRoute = PrivateLogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateCodesRoute = PrivateCodesImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateClientsRoute = PrivateClientsImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAsociatesRoute = PrivateAsociatesImport.update({
  id: '/asociates',
  path: '/asociates',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateUserIdRoute = PrivateUserIdImport.update({
  id: '/user_/$id',
  path: '/user/$id',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateTasksTaskIdRoute = PrivateTasksTaskIdImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProjectsProjectIdRoute = PrivateProjectsProjectIdImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PrivateRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_private/asociates': {
      id: '/_private/asociates'
      path: '/asociates'
      fullPath: '/asociates'
      preLoaderRoute: typeof PrivateAsociatesImport
      parentRoute: typeof PrivateImport
    }
    '/_private/clients': {
      id: '/_private/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof PrivateClientsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/codes': {
      id: '/_private/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof PrivateCodesImport
      parentRoute: typeof PrivateImport
    }
    '/_private/logout': {
      id: '/_private/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PrivateLogoutImport
      parentRoute: typeof PrivateImport
    }
    '/_private/projects': {
      id: '/_private/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PrivateProjectsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/resources': {
      id: '/_private/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PrivateResourcesImport
      parentRoute: typeof PrivateImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_public/task': {
      id: '/_public/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof PublicTaskImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_private/projects_/$projectId': {
      id: '/_private/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof PrivateProjectsProjectIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/tasks/$taskId': {
      id: '/_private/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof PrivateTasksTaskIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/user_/$id': {
      id: '/_private/user_/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof PrivateUserIdImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateAsociatesRoute: typeof PrivateAsociatesRoute
  PrivateClientsRoute: typeof PrivateClientsRoute
  PrivateCodesRoute: typeof PrivateCodesRoute
  PrivateLogoutRoute: typeof PrivateLogoutRoute
  PrivateProjectsRoute: typeof PrivateProjectsRoute
  PrivateResourcesRoute: typeof PrivateResourcesRoute
  PrivateProjectsProjectIdRoute: typeof PrivateProjectsProjectIdRoute
  PrivateTasksTaskIdRoute: typeof PrivateTasksTaskIdRoute
  PrivateUserIdRoute: typeof PrivateUserIdRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateAsociatesRoute: PrivateAsociatesRoute,
  PrivateClientsRoute: PrivateClientsRoute,
  PrivateCodesRoute: PrivateCodesRoute,
  PrivateLogoutRoute: PrivateLogoutRoute,
  PrivateProjectsRoute: PrivateProjectsRoute,
  PrivateResourcesRoute: PrivateResourcesRoute,
  PrivateProjectsProjectIdRoute: PrivateProjectsProjectIdRoute,
  PrivateTasksTaskIdRoute: PrivateTasksTaskIdRoute,
  PrivateUserIdRoute: PrivateUserIdRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicTaskRoute: typeof PublicTaskRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicTaskRoute: PublicTaskRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/asociates': typeof PrivateAsociatesRoute
  '/clients': typeof PrivateClientsRoute
  '/codes': typeof PrivateCodesRoute
  '/logout': typeof PrivateLogoutRoute
  '/projects': typeof PrivateProjectsRoute
  '/resources': typeof PrivateResourcesRoute
  '/login': typeof PublicLoginRoute
  '/task': typeof PublicTaskRoute
  '/': typeof PublicIndexRoute
  '/projects/$projectId': typeof PrivateProjectsProjectIdRoute
  '/tasks/$taskId': typeof PrivateTasksTaskIdRoute
  '/user/$id': typeof PrivateUserIdRoute
}

export interface FileRoutesByTo {
  '': typeof PrivateRouteWithChildren
  '/asociates': typeof PrivateAsociatesRoute
  '/clients': typeof PrivateClientsRoute
  '/codes': typeof PrivateCodesRoute
  '/logout': typeof PrivateLogoutRoute
  '/projects': typeof PrivateProjectsRoute
  '/resources': typeof PrivateResourcesRoute
  '/login': typeof PublicLoginRoute
  '/task': typeof PublicTaskRoute
  '/': typeof PublicIndexRoute
  '/projects/$projectId': typeof PrivateProjectsProjectIdRoute
  '/tasks/$taskId': typeof PrivateTasksTaskIdRoute
  '/user/$id': typeof PrivateUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/asociates': typeof PrivateAsociatesRoute
  '/_private/clients': typeof PrivateClientsRoute
  '/_private/codes': typeof PrivateCodesRoute
  '/_private/logout': typeof PrivateLogoutRoute
  '/_private/projects': typeof PrivateProjectsRoute
  '/_private/resources': typeof PrivateResourcesRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/task': typeof PublicTaskRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/projects_/$projectId': typeof PrivateProjectsProjectIdRoute
  '/_private/tasks/$taskId': typeof PrivateTasksTaskIdRoute
  '/_private/user_/$id': typeof PrivateUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/asociates'
    | '/clients'
    | '/codes'
    | '/logout'
    | '/projects'
    | '/resources'
    | '/login'
    | '/task'
    | '/'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/asociates'
    | '/clients'
    | '/codes'
    | '/logout'
    | '/projects'
    | '/resources'
    | '/login'
    | '/task'
    | '/'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/user/$id'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/asociates'
    | '/_private/clients'
    | '/_private/codes'
    | '/_private/logout'
    | '/_private/projects'
    | '/_private/resources'
    | '/_public/login'
    | '/_public/task'
    | '/_public/'
    | '/_private/projects_/$projectId'
    | '/_private/tasks/$taskId'
    | '/_private/user_/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_private",
        "/_public"
      ]
    },
    "/_private": {
      "filePath": "_private.jsx",
      "children": [
        "/_private/asociates",
        "/_private/clients",
        "/_private/codes",
        "/_private/logout",
        "/_private/projects",
        "/_private/resources",
        "/_private/projects_/$projectId",
        "/_private/tasks/$taskId",
        "/_private/user_/$id"
      ]
    },
    "/_public": {
      "filePath": "_public.jsx",
      "children": [
        "/_public/login",
        "/_public/task",
        "/_public/"
      ]
    },
    "/_private/asociates": {
      "filePath": "_private/asociates.jsx",
      "parent": "/_private"
    },
    "/_private/clients": {
      "filePath": "_private/clients.jsx",
      "parent": "/_private"
    },
    "/_private/codes": {
      "filePath": "_private/codes.jsx",
      "parent": "/_private"
    },
    "/_private/logout": {
      "filePath": "_private/logout.jsx",
      "parent": "/_private"
    },
    "/_private/projects": {
      "filePath": "_private/projects.jsx",
      "parent": "/_private"
    },
    "/_private/resources": {
      "filePath": "_private/resources.jsx",
      "parent": "/_private"
    },
    "/_public/login": {
      "filePath": "_public/login.jsx",
      "parent": "/_public"
    },
    "/_public/task": {
      "filePath": "_public/task.jsx",
      "parent": "/_public"
    },
    "/_public/": {
      "filePath": "_public/index.jsx",
      "parent": "/_public"
    },
    "/_private/projects_/$projectId": {
      "filePath": "_private/projects_.$projectId.jsx",
      "parent": "/_private"
    },
    "/_private/tasks/$taskId": {
      "filePath": "_private/tasks.$taskId.jsx",
      "parent": "/_private"
    },
    "/_private/user_/$id": {
      "filePath": "_private/user_.$id.jsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
